### PR TITLE
Fixing pagination in fetchPrevious function

### PR DESCRIPTION
**Pull request by buzzeante**
- Prepending new fetched models to the collection.
- When reaching the first page only retrieve missing models.

Hi there, thanks for your library. Great work.

Cheers,
Javier

### CODE REVIEW

**Comment by buzzeante** [comment]
Indeed I could use a comparator, but I think that the default behaviour of `fetchPrevious` should be prepending models retrieved. The only use case I can think of where `fetchPrevious` appends models to the collection instead of prepending is when order does not really matter.

The second change is only to make `fetchPrevious` more efficient in the case where you get to the first page. If the offset is < 0 means that the page you need to retrieve is smaller than the limit; hence in the fix I adapt the limit so that it only requests the elements that are not already in the collection, avoiding double-requesting them.

Cheers,
Javier

**Comment by amccloud** [comment]
Okay, I somewhat agree about the prepending. Simple relying on the fetch functions to correctly order things is not gonna cut it. If order truly matters you need to be using a comparator. Just because you prepend the previous results does not necessarily mean things will be properly ordered.

If you submit the offset improvements in a separate PR i'll go ahead and merge it in.

**Comment by maraujop** [comment]
> Okay, I somewhat agree about the prepending. Simple relying on the fetch functions to correctly order things is not gonna cut it. If order truly matters you need to be using a comparator. Just because you prepend the previous results does not necessarily mean things will be properly ordered.

Andrew, we've been discussing this and I think that prepending doesn't solve the order problem, but it should be the default behavior. 

If you set an order by passing parameters to the API using `data` (you get things ordered from the backend, which avoids repeating work in the frontend). The previous page, will have to go before the current one, not after, as its name indicates. I can see many use cases where this helps us (but doesn't affect others that don't rely on order, they don't care prepending or appending), but I cannot think of any use case where the legit default would be appending. 

This way, we avoid comparators, double doing work and slowing the user interface response time. What do you think?

Thanks for solving the other bug that fast, we appreciate your fast response time.

Cheers,
Miguel

**Comment by amccloud** [comment]
Okay so I think we'll just do the prepending so things are in roughly sorted order. I still believe that you should always be using a collection comparator if order really matters.

**Pull request merged**
